### PR TITLE
Grant Life Membership to James Dearlove

### PR DESCRIPTION
**Pull request by q-horton**
I had not realised this was a special resolution thing, had intended to catch them off guard at the AGM. Thanks to Sigma's mass updates for helping to realise this.

I can't speak to any specifics of Jimmy's contributions during his time in office as I only became a member of UQCS the year after his reign ended. Despite that, I could not imagine that helming the club off the back of the pandemic that shut down socialising as we knew it was any easy feat. I can however confidently say that despite no longer being a student or a UQCS exec, Jimmy's contributions are still not over and clear to see almost two years on.

Thus, I only think it is fair to submit :ghostJimmy: for life membership.

### CODE REVIEW

**Comment by RachelChiong** [comment]
More to come (@Thomas-Malcolm) 👀

**Comment by Thomas-Malcolm** [comment]
My first memory of Jimmy is the hackathon from "2020" (2021) - he was energetic, enthusiastic, and exceedingly welcoming to all who approached him. And he had short hair. That energy and enthusiasm doubtlessly helped contribute to the positive environment we have in our club, and in my opinion is exactly what committee should strive to achieve - an attitude which was immensely important during the difficulties of covid as well, which Jimmy took in stride and used to help lead the club, keeping it afloat and thriving. During his presidency Jimmy dedicated much (read: too much) of his personal time and energy directly into the club, and if even if he had finished his term and never looked back, we would still look back on his years in the society as being incredibly formative and successful in shaping the club to be what it is today. But he didn't stop there. Even after finishing up his time on committee, and even after graduating, Jimmy has been one of the more consistent attendees of events, always ready to offer his seemingly limitless UQCS knowledge to anyone in need. Whether helping set up and run livestreams, answering questions at hackathon, or shitposting on discord, it's hard to imagine a period of UQCS in recent history where Jimmy hasn't been there to lend a hand. We should also note the significant contributions to infrastructure Jimmy has had - a non exhaustive list including the transition from Slack to Discord, the migration from UQ web services to Azure, UQCS bot, and UQCSPay. He is always happy to help, his insight has saved committee on more than one occasion (as I can personally attest to), and more than anything, he lives and breathes this society.

Jimmy long ago earned his status as a staple of UQCS, and in my opinion is the very definition of a life member - he deserved this title, if for nothing more than to ensure that he :dont_forget_youre_here_forever:.

**Comment by RachelChiong** [comment]
Jimmy often does things unprovoked and hidden in the background to UQCS members. However, today is the day that we bring many of these to light and really appreciate and recognise Jimmy’s invaluable contributions to this society. 

Despite officially leaving committee at the end of 2021 and graduating in 2022, Jimmy’s contribution to the society has extended beyond that. Jimmy has been and continues to maintain UQCS infrastructure, including our website, payment systems, GitHub and Discord bot and has been the point of call for many committee members when something in either of these spaces goes awry or require further attention. 

Additionally, Jimmy, along with Paul overhauled the UQCS membership payment system, creating UQCSPay earlier this year. This membership payment system has been super useful for committee when managing members, and is something that SMACK have also been able to take advantage of. At the Hackathon this year, many members were able to lean on his expertise and good will, as he had become the unofficial git and tooling expert. Jimmy did not need to do this, and could have easily handed-off all of these questions to committee members, but he chose to help out instead. 

Not only at a technical level, but Jimmy has been the go to person to ask questions about streaming equipment and the general runnings of the society. Whenever myself, or other committee members wanted a second opinion, we could count on Jimmy to step up and provide assistance. If there’s something that needs to be done, or addressed - both online and offline, you can be certain that Jimmy will be there to either alleviate the pain point or alert committee, unprovoked and with enthusiasm. UQCS is very lucky to have an ex-President and member who cares so much about the club, who really puts words into action and brings ideas to life. You could also count on him for making some incredible shitposts and being thoroughly entertaining. 

It has been an absolute privilege working alongside Jimmy, who has been an excellent role model for what a UQCS member can be. For these reasons, and those outlined by Quinn and Tom, I could not think of a better person to grant life membership to.

**Comment by LimaoC** [comment]
Motion passed by 2/3 vote @ 05/10/2023 AGM

**Pull request merged**
