### PR TITLE
Grant Life Membership to Taylor Manderson

### PR DESCRIPTION
**Pull request by bradleysigma**
I am proposing a special resolution to grant life membership for UQCS to Taylor Manderson. I believe this is long overdue.
Taylor has met what I believe are the two conditions necessary for life membership: a) outstanding contributions to the society while a student at UQ; and b) outstanding contributions to the society following graduation.
For the former condition, the bulk of that was before my time, but Taylor served on the committee for four years, two of which as president. In that time, the UQCS Slack was instituted, which was the main communication platform for six years until 2021.
For the latter condition, Taylor has remained an active member of the UQCS community after graduating. She maintains a presence on the UQCS Discord, offering advice and anecdotes wherever needed. So far in 2023, she has sent 1027 messages on the UQCS Discord, about the same as the as the president, secretary, treasurer and committee account have sent combined\*. In addition, she has served as a judge multiple times at the UQCS Hackathon. For a long time after leaving committee, she helped maintain much of the UQCS technical infrastructure.
\* NB: I don't wish to encourage the spamming of the Discord, and life membership shouldn't be granted based only on Discord messages, but it does serve as a coarse metric.
I can't think of any member more deserving of life membership than Taylor.

### CODE REVIEW

**Comment by lsenjov** [comment]
As someone who's been in and around UQCS for years, TRM absolutely deserves this. She's led or supported UQCS and been a constant mentor.

**Review by nicklambourne — APPROVED** [review]
Agreed, no-one has done more to deserve this, in my humble opinion.

**Comment by JamesDearlove** [comment]
Also agreed, UQCS wouldn't be where it is today without her ongoing contributions and definitely deserves this.

**Comment by LimaoC** [comment]
Motion passed by 2/3 vote @ 05/10/2023 AGM

**Pull request merged**
