### PR TITLE
Create committee_history.md

### PR DESCRIPTION
**Pull request by bradleysigma**

### CODE REVIEW

**Comment by jdcaperon** [comment]
Is it worth defining how mid-term changes to positions should be listed for future, or potentially past, reference?

**Comment by jdcaperon** [comment]
I think dates should be fine, e.g.

```
  - Jack Caperon (Resigned - 20/05/20)
  - Paul Clarke (Elected - 20/05/20)
```

Or some other method. Could even just be tagged with (Resigned Early) to indicate it.

**Review by nicklambourne — APPROVED** [review]

**Comment by jdcaperon** [comment]
Can we do the mid-term things to make it obvious we don't have confusingly large committees

**Comment by nicklambourne** [comment]
I will try and track down the relevant info today.

**Comment by jdcaperon** [comment]
It doesn't have to be specific dates historically, just something that sets a precedent.

**Comment by bradleysigma** [comment]
The dates look... inelegant.

**Comment by nicklambourne** [comment]
> The dates look... inelegant.

Make a suggestion then

**Comment by jdcaperon** [comment]
```
- Puisne Committee:
  - Alexander Blyth - Elected by SGM 03-05-20
  - Sannidhi Bosamia
  - Jack Caperon - Resigned 03-05-20
  - Paul Clarke - Elected by SGM 03-05-20
  - James Copperthwaite
  - James Dearlove - Elected by SGM 03-05-20
```

**Comment by jdcaperon** [comment]
I don't think it really matters... it's just a record

**Review by jdcaperon — APPROVED** [review]

**Pull request merged**
